import { Author } from "./types";

export const SEED_AUTHORS: Partial<Author>[] = [
  {
    slug: "marisol-vega",
    name: "Marisol Vega",
    tagline: "Bilingual picture-book author & illustrator",
    bio: "Marisol Vega writes bilingual picture books that celebrate Latino heritage and the magic of everyday moments. Her books have been featured in School Library Journal and named to the Pura Belpré Honor list. She has visited over 80 schools across the country and brings her illustrations to life with live-drawing demonstrations that leave kids buzzing.",
    location_city: "San Diego",
    location_state: "CA",
    genres: ["Picture Books", "Bilingual", "Cultural Stories"],
    grade_range: ["K–2", "3–5"],
    languages: ["English", "Spanish"],
    books: [
      { title: "The Color of Home", year: 2021, publisher: "Scholastic", cover_color: "#C7522A", type: "picture_book" },
      { title: "Mija, the Moon Knows", year: 2022, publisher: "Scholastic", cover_color: "#2E8B6F", type: "picture_book" },
      { title: "Where Tamales Come From", year: 2023, publisher: "Scholastic", cover_color: "#3A5A8C", type: "picture_book" },
    ],
    visit_offerings: [
      { kind: "local", base_price: 650, unit: "day", local_radius_miles: 30, includes: ["3 read-aloud assemblies", "Live drawing demo", "Small-group Q&A", "Signed book for library"] },
      { kind: "out_of_area", base_price: 650, unit: "day", travel_policy: "at_cost", includes: ["Everything in local visit", "Full-day minimum", "Travel logistics handled"] },
      { kind: "virtual", base_price: 300, unit: "session", includes: ["45-min live video session", "Read-aloud + screen-shared illustration", "Student Q&A", "Activity sheet sent ahead"] },
    ],
    local_radius_miles: 30,
    offers_grant_visits: true,
    grant_visits_per_year: 5,
    grant_visits_remaining: 3,
    offers_title1_subsidy: true,
    offers_free_virtual_qa: true,
    website_url: "https://marisolvega.com",
    booking_url: "https://marisolvega.com",
    status: "active",
  },
  {
    slug: "james-okonkwo",
    name: "James Okonkwo",
    tagline: "Middle-grade adventure author",
    bio: "James writes heart-pounding middle-grade adventures that show kids from all backgrounds as the heroes. His debut trilogy has sold over 200,000 copies. School visits are his favorite days of the year.",
    location_city: "Chicago",
    location_state: "IL",
    genres: ["Middle Grade", "Adventure", "Diverse Heroes"],
    grade_range: ["3–5", "6–8"],
    languages: ["English"],
    books: [
      { title: "The Iron Compass", year: 2020, publisher: "HarperCollins", cover_color: "#3A5A8C", type: "middle_grade" },
      { title: "Storm Riders", year: 2021, publisher: "HarperCollins", cover_color: "#7C6A9C", type: "middle_grade" },
      { title: "The Last Cartographer", year: 2023, publisher: "HarperCollins", cover_color: "#E2A93B", type: "middle_grade" },
    ],
    visit_offerings: [
      { kind: "local", base_price: 700, unit: "day", local_radius_miles: 50, includes: ["Author talk", "Writing workshop", "Q&A session", "Book signing"] },
      { kind: "virtual", base_price: 350, unit: "session", includes: ["60-min virtual talk", "Writing craft Q&A", "Slide presentation"] },
    ],
    local_radius_miles: 50,
    offers_grant_visits: true,
    grant_visits_per_year: 3,
    grant_visits_remaining: 2,
    offers_title1_subsidy: false,
    offers_free_virtual_qa: true,
    booking_url: "mailto:visits@jamesokonkwo.com",
    status: "active",
  },
  {
    slug: "priya-mehta",
    name: "Priya Mehta",
    tagline: "Science picture books & STEM literacy",
    bio: "Priya's picture books make science accessible and joyful for young readers. She holds a PhD in biology and has a gift for turning complex ideas into stories kids beg to hear again.",
    location_city: "Boston",
    location_state: "MA",
    genres: ["STEM", "Picture Books", "Nonfiction"],
    grade_range: ["K–2", "3–5"],
    languages: ["English"],
    books: [
      { title: "The Bee Who Asked Why", year: 2022, publisher: "Penguin Random House", cover_color: "#E2A93B", type: "picture_book" },
      { title: "Stars Are Giant Suns", year: 2023, publisher: "Penguin Random House", cover_color: "#3A5A8C", type: "picture_book" },
    ],
    visit_offerings: [
      { kind: "local", base_price: 600, unit: "day", local_radius_miles: 40, includes: ["STEM read-aloud", "Simple science demo", "Q&A", "Activity worksheet"] },
      { kind: "virtual", base_price: 275, unit: "session", includes: ["45-min virtual STEM session", "Live experiment demo", "Q&A"] },
    ],
    local_radius_miles: 40,
    offers_grant_visits: false,
    grant_visits_per_year: 0,
    grant_visits_remaining: 0,
    offers_title1_subsidy: true,
    offers_free_virtual_qa: false,
    status: "active",
  },
  {
    slug: "derek-washington",
    name: "Derek Washington",
    tagline: "Poetry & spoken word for young readers",
    bio: "Derek brings the energy of spoken word to school visits that leave kids wanting to write their own poems. His debut collection won the Coretta Scott King Honor.",
    location_city: "Atlanta",
    location_state: "GA",
    genres: ["Poetry", "Middle Grade", "Cultural Stories"],
    grade_range: ["3–5", "6–8"],
    languages: ["English"],
    books: [
      { title: "Words That Break Walls", year: 2021, publisher: "Lee & Low Books", cover_color: "#C7522A", type: "middle_grade" },
      { title: "Every Poem Is a Fist", year: 2024, publisher: "Lee & Low Books", cover_color: "#2E8B6F", type: "middle_grade" },
    ],
    visit_offerings: [
      { kind: "local", base_price: 750, unit: "day", local_radius_miles: 60, includes: ["Spoken-word performance", "Poetry writing workshop", "Group share-out", "Signed copy for library"] },
      { kind: "out_of_area", base_price: 750, unit: "day", travel_policy: "at_cost", includes: ["Full performance + workshop", "Travel arranged together"] },
      { kind: "virtual", base_price: 300, unit: "session", includes: ["45-min performance", "Writing prompt + share-out", "Q&A"] },
    ],
    local_radius_miles: 60,
    offers_grant_visits: true,
    grant_visits_per_year: 4,
    grant_visits_remaining: 4,
    offers_title1_subsidy: true,
    offers_free_virtual_qa: true,
    booking_url: "https://derekwashingtonpoet.com/visits",
    status: "active",
  },
];

export const COVER_COLORS = ["#C7522A", "#2E8B6F", "#3A5A8C", "#E2A93B", "#7C6A9C"];
